// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SadcOms.Infrastructure.Persistence;

#nullable disable

namespace SadcOms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250601090500_AddOrderRowVersion")]
    partial class AddOrderRowVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SadcOms.Domain.Customers.Customer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CountryCode")
                    .IsRequired()
                    .HasMaxLength(2)
                    .HasColumnType("nchar(2)")
                    .IsFixedLength();

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("nvarchar(320)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("Name");

                b.ToTable("Customers");
            });

            modelBuilder.Entity("SadcOms.Domain.Orders.Order", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CurrencyCode")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("nchar(3)")
                    .IsFixedLength();

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<decimal>("TotalAmount")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("CustomerId", "Status", "CreatedAt")
                    .HasDatabaseName("IX_Orders_CustomerId_Status_CreatedAt");

                b.HasIndex("Status", "CreatedAt")
                    .HasDatabaseName("IX_Orders_Status_CreatedAt");

                b.ToTable("Orders");
            });

            modelBuilder.Entity("SadcOms.Domain.Orders.OrderLineItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("OrderId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ProductSku")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<decimal>("UnitPrice")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.ToTable("OrderLineItems");
            });

            modelBuilder.Entity("SadcOms.Domain.Orders.Order", b =>
            {
                b.HasOne("SadcOms.Domain.Customers.Customer", null)
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("SadcOms.Domain.Orders.OrderLineItem", b =>
            {
                b.HasOne("SadcOms.Domain.Orders.Order", null)
                    .WithMany("LineItems")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("SadcOms.Domain.Orders.Order", b =>
            {
                b.Navigation("LineItems");
            });
#pragma warning restore 612, 618
        }
    }
}
